---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - log.aiops.com
  resources:
  - logpilots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - log.aiops.com
  resources:
  - logpilots/finalizers
  verbs:
  - update
- apiGroups:
  - log.aiops.com
  resources:
  - logpilots/status
  verbs:
  - get
  - patch
  - update
