# permissions for end users to view applicaitons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/managed-by: kustomize
  name: applicaiton-viewer-role
rules:
- apiGroups:
  - application.aiops.com
  resources:
  - applicaitons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.aiops.com
  resources:
  - applicaitons/status
  verbs:
  - get
