---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - application.aiops.com
  resources:
  - applicaitons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.aiops.com
  resources:
  - applicaitons/finalizers
  verbs:
  - update
- apiGroups:
  - application.aiops.com
  resources:
  - applicaitons/status
  verbs:
  - get
  - patch
  - update
